Algoritmo "Algoritimo 3"
 //Escreva um algoritmo para ler dois valores (considere
 // que não serão lidos valores iguais) e escrever o maior
 // deles.

Var
va:real
vb:real


Inicio
escreval("Me dê a altura de duas pessoas, e eu direi qual o maior")
escreval("primeira pessoa:")
leia(va)
escreval("segunda pessoa:")
leia(vb)

  se va>vb entao
  escreval("A primeira é maior.")
  fimse
  
  se vb>va entao
  escreval("o segundo é maior.")
  fimse



Fimalgoritmo