Algoritmo "temperatura Fahrenheit em celsius "
//Faça um algoritmo que lê uma temperatura em Fahrenheit e
//calcula a temperatura correspondente em Celsius. Ao final
//o programa deve exibir as
//duas temperaturas.
//– Usar a fórmula: C = (5 * (F-32) / 9)
Var
Fahrenheit:real

Inicio
escreval("Informe a temperatura em Fahrenheit:")
leia(Fahrenheit)
escreval("Temperatura em Fahrenheit: ",Fahrenheit)
escreval("Temperatura em celsius: ",5*(Fahrenheit-32)/9)

Fimalgoritmo